log4j.rootLogger = ERROR,Console

#\u63A7\u5236\u53F0\u65E5\u5FD7
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.Target=System.out
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern = [%d{ISO8601}] [%c] [%-5p] - %m%n
log4j.appender.Console.datePattern = '.'yyyy-MM-dd
log4j.appender.Console.append = true
log4j.appender.Console.encoding = UTF-8

#sql log
log4j.logger.com.ibatis=DEBUG
log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=DEBUG
log4j.logger.com.ibatis.common.jdbc.ScriptRunner=DEBUG
log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG
log4j.logger.java.sql.Connection=DEBUG
log4j.logger.java.sql.Statement=DEBUG
log4j.logger.java.sql.PreparedStatement=DEBUG
log4j.logger.com.hd.dao.generator.ArticleGeneratorMapper=TRACE


#spring log
log4j.logger.org.springframework = ERROR,ibatis

#hd log
log4j.logger.redislog = ERROR,redis
log4j.logger.cachelog = ERROR,ibatis
log4j.logger.caslog = ERROR,ibatis
log4j.logger.hdlog = info,ibatis

#config
log4j.additivity.ibatis = ERROR
log4j.appender.ibatis.encoding = UTF-8
log4j.logger.ibatis = ERROR,ibatis
log4j.appender.ibatis = org.apache.log4j.DailyRollingFileAppender
log4j.appender.ibatis.layout = org.apache.log4j.PatternLayout
log4j.appender.ibatis.layout.ConversionPattern = [%d{ISO8601}] [%c] [%-5p] - %m%n
log4j.appender.ibatis.datePattern = '.'yyyy-MM-dd
log4j.appender.ibatis.append = true
log4j.appender.ibatis.File = /usr/local/tomcat/logs/front/mall-front.log

#redis
log4j.additivity.redis = ERROR
log4j.appender.redis.encoding = UTF-8
log4j.logger.redis = ERROR,ibatis
log4j.appender.redis = org.apache.log4j.DailyRollingFileAppender
log4j.appender.redis.layout = org.apache.log4j.PatternLayout
log4j.appender.redis.layout.ConversionPattern = [%d{ISO8601}] [%c] [%-5p] - %m%n
log4j.appender.redis.datePattern = '.'yyyy-MM-dd
log4j.appender.redis.append = true
log4j.appender.redis.File = /usr/local/tomcat/logs/front/redis.log
