#skiing配置文件
logisticsKey=RJVPGTlS8596
logisticsCustomer=8A1D4CE84AFD3B8B5CCA05C91A138CA1
logisticsUrl=https://poll.kuaidi100.com/poll/query.do
logisticsCompanyUrl=http://www.kuaidi100.com/autonumber/auto