#redis\u914D\u7F6E\u6587\u4EF6
redisIp=r-m5efe79516e19bf4.redis.rds.aliyuncs.com:6379:4
redispw=hongdingRedis951147

#0 雪托帮 1如e生活 2:accessToken（具体哪个项目用的不知道）  3：齐齐哈尔答题 4：寻找朗读者   5：车微信授权

accessTokenRedisIp=r-m5efe79516e19bf4.redis.rds.aliyuncs.com:6379:2
accessTokenPassword=hongdingRedis951147